author/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.about_me, name='author'),
]

flavour/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path("author/", include("author.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", include("recipe.urls"), name="recipe-urls"),
]

recipe/urls.py
from django.urls import path, include
from recipe import views
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.RecipeList.as_view(), name='home'),
    path('chef-special/', views.chef_special, name='chef_special'),
    path('share/', views.share_recipe, name='share_recipe'),
    path('<slug:slug>/', views.recipe_detail, name='recipe_detail'),
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
]

recipe/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.dispatch import receiver


STATUS = (
    (0, 'Draft'),
    (1, 'Published'),
    )
DIET = (
    (0, 'Vegetarian'),
    (1, 'Non-Vegetarian'),
    (2, 'Vegan'),
    (3, 'Other'),
    )
RATING_STARS = (
        (1, '⭐'),
        (2, '⭐⭐'),
        (3, '⭐⭐⭐'),
        (4, '⭐⭐⭐⭐'),
        (5, '⭐⭐⭐⭐⭐'),
    )


# Create your models here.
class Recipe(models.Model):
    recipe_id = models.AutoField(primary_key=True)
    recipe_title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    author = models.ForeignKey(User, related_name='recipe_author',
                               on_delete=models.CASCADE)
    featured_image = CloudinaryField('image', default='placeholder')
    diet = models.IntegerField(choices=DIET, default=3)
    introduction = models.TextField()
    ingredients = models.TextField()
    instructions = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)
    excerpt = models.TextField(max_length=500, blank=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"{self.recipe_title} | written by {self.author}"


@receiver(pre_save, sender=Recipe)
def generate_slug(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.recipe_title)
        unique_slug = instance.slug
        num = 1
        while Recipe.objects.filter(slug=unique_slug).exists():
            unique_slug = f"{instance.slug}-{num}"
            num += 1
        instance.slug = unique_slug


class Comment(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,
                               related_name="comments")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commenter")
    rating = models.IntegerField(choices=RATING_STARS, default=1)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.author}"

recipe/forms.py
from .models import Recipe, Comment, RATING_STARS
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body', 'rating']
        widgets = {
            'body': forms.Textarea(attrs={'rows': 4}),
        }


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['recipe_title', 'featured_image', 'diet', 'introduction',
                  'ingredients', 'instructions']
        widgets = {
            'introduction': forms.Textarea(attrs={'rows': 4}),
        }

    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.required = True

recipe/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Recipe, Comment
from author.models import Author
from .forms import CommentForm
from .forms import RecipeForm
from django.db.models import F


@login_required
def chef_special(request):
    # Check if the user is authenticated
    if request.user.is_authenticated:
        # Get all author titles
        author_titles = Author.objects.values_list('title', flat=True)
        # Filter recipes where the author's username matches
        # any title in the Author model
        recipes = Recipe.objects.filter(author__username__in=author_titles,
                                        status=1)
        return render(request, 'recipe/chef_special.html',
                      {'recipe_list': recipes})
    else:
        # Redirect to the login page with a 'next' parameter
        return redirect('account_login')


class RecipeList(generic.ListView):
    """
    Returns all published recipes in :model:`recipe.Recipe`
    and displays them in a page of six recipes.
    **Context**

    ``queryset``
        All published instances of :model:`recipe.Recipe`
    ``paginate_by``
        Number of recipes per page.

    **Template:**

    :template:`recipe/index.html`
    """

    queryset = Recipe.objects.all().filter(status=1)
    template_name = "recipe/index.html"
    paginate_by = 6

    def get_queryset(self):
        recipes = Recipe.objects.filter(status=1)
        print("All Recipes:", recipes)  # Debug print
        author_titles = Author.objects.values_list('title', flat=True)
        filtered_recipes = recipes.exclude(author__username__in=author_titles)
        print("Filtered Recipes (excluding admin):", filtered_recipes)
        return filtered_recipes


def recipe_detail(request, slug):
    """
    Display an individual :model:`recipe.Recipe`.

    **Context**

    ``recipe``
        An instance of :model:`recipe.Recipe`.

    **Template:**

    :template:`recipe/recipe_detail.html`
    """
    queryset = Recipe.objects.filter(status=1)
    recipe = get_object_or_404(queryset, slug=slug)
    comments = recipe.comments.all().order_by("-created_on")
    comment_count = recipe.comments.filter(approved=True).count()

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.recipe = recipe
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Comment submitted and awaiting approval'
            )

    comment_form = CommentForm()

    return render(
        request,
        "recipe/recipe_detail.html",
        {
            "recipe": recipe,
            "comments": comments,
            "comment_count": comment_count,
            "comment_form": comment_form,
        }
    )


def comment_edit(request, slug, comment_id):
    """
    view to edit comments
    """
    if request.method == "POST":

        queryset = Recipe.objects.filter(status=1)
        recipe = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        print("Comment:", comment)  # Debug print
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.recipe = recipe
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Comment Updated!')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Error updating comment!')

    return HttpResponseRedirect(reverse('recipe_detail', args=[slug]))


def comment_delete(request, slug, comment_id):
    """
    view to delete comment
    """
    queryset = Recipe.objects.filter(status=1)
    recipe = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(request, messages.ERROR,
                             'You can only delete your own comments!')

    return HttpResponseRedirect(reverse('recipe_detail', args=[slug]))


@login_required
def share_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.status = 0  # Set status to 'Draft' for admin approval
            recipe.save()
            messages.add_message(request, messages.SUCCESS,
                                 "Thanks for sharing your recipe! It's on "
                                 "its way for approval and will be live in "
                                 "the Recipe section once it's approved. "
                                 "Stay tuned!")
            form = RecipeForm()
            # return redirect('home')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Error submitting recipe!')
    else:
        form = RecipeForm()
    return render(request, 'recipe/share_recipe.html', {'form': form})

recipe/templates/recipe/chef_special.html
{% extends "base.html" %}

{% load static %}

{% block title %}Chef's Special{% endblock %}

{% block link %}
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
<!-- Chef's Special Header -->
<div class="container-fluid text-center mt-4">
    <h1>Chef's Special Recipes</h1>
    <p class="lead">Curated exclusively by our <strong>skilled chefs</strong> for the finest culinary experiences.</p>
</div>

<!-- Recipe Posts -->
<div class="container-fluid mt-3  mb-4">
    <div class="row">
        <!-- Recipe Entries Column -->
        <div class="col-12 mt-3">
            <div class="row">
                {% for recipe in recipe_list %}
                                   
                        <div class="col-md-4">
                            <div class="card mb-4 recipe-entry">
                                <div class="card-body">
                                    <div class="image-container mb-3">
                                        {% if "placeholder" in recipe.featured_image.url %}
                                            <img class="card-img-top" src="{% static 'images/default.jpg' %}" alt="placeholder image">
                                        {% else %}
                                            <img class="card-img-top" src="{{ recipe.featured_image.url }}" alt="{{ recipe.recipe_title }}">
                                        {% endif %}
                                       
                                    </div>
                                    <a href="{% url 'recipe_detail' recipe.slug %}" class="recipe-link">
                                        <h2 class="card-title">{{ recipe.recipe_title }}</h2>
                                    </a>
                                    <p class="introduction">{{ recipe.introduction }}</p>
                                    <hr>
                                    <div class="image-flash d-flex justify-content-between align-items-center">
                                        <p class="author mb-0">Recipe By: <strong>{{ recipe.author }}</strong></p>
                                        <p class="card-text text-muted h6 mb-0">{{ recipe.get_diet_display}}
                                        </p>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:3 %}
                            </div><div class="row">
                        {% endif %}
                    
                {% empty %}
                    <div class="col-12">
                        <p class="text-center fs-4">No special recipes from Admin at the moment. Check back soon!</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {% if is_paginated %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV</a>
                    </li>
                {% endif %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link">NEXT &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
</div>
{% endblock %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

recipe/templates/recipe/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}Home{% endblock %}

{% block link %}
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}

<!-- *** Hero Carousel *** -->
<!-- Half and half carousel style starts -->
<div id="carouselExample" class="carousel slide mb-3 mt-4" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active flex-wrap">
            <div class="row g-0">
                <div class="col-lg-8 col-md-8 col-sm-12">
                    <video class="w-100" autoplay muted loop>
                        <source src="{% static 'videos/saute.mp4' %}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </div>
                <div class="carousel-content col-lg-4 col-md-4 col-sm-12 d-flex align-items-center justify-content-center">
                    <div class="p-4 text-center">
                        <h3 class="fs-1 font-style">Flavors That Tell a Story, Ingredients That Matter</h3>
                        <div class="carousel-indicators position-static pt-5">
                            <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                            <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="1" aria-label="Slide 2"></button>
                            <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="2" aria-label="Slide 3"></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="row g-0">
                <div class="col-lg-8 col-md-8 col-sm-12">
                    <video class="w-100" autoplay muted loop>
                        <source src="{% static 'videos/pasta.mp4' %}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </div>
                <div class="carousel-content col-lg-4 col-md-4 col-sm-12 d-flex align-items-center justify-content-center">
                    <div class="p-4 text-center">
                        <h3 class="fs-1 font-style">Crave-Worthy Creations, Perfectly Plated</h3>
                        <div class="carousel-indicators position-static pt-5">
                            <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="0" aria-label="Slide 1"></button>
                            <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="1" class="active" aria-current="true" aria-label="Slide 2"></button>
                            <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="2" aria-label="Slide 3"></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="row g-0">
                <div class="col-lg-8 col-md-8 col-sm-12">
                    <video class="w-100" autoplay muted loop>
                        <source src="{% static 'videos/pancake.mp4' %}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </div>
                <div class="carousel-content col-lg-4 col-md-4 col-sm-12 d-flex align-items-center justify-content-center">
                    <div class="p-4 text-center">
                        <h3 class="fs-1 font-style">Indulge in Every Bite: Where Taste Meets Art</h3>
                        <div class="carousel-indicators position-static pt-5">
                            <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="0" aria-label="Slide 1"></button>
                            <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="1" aria-label="Slide 2"></button>
                            <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="2" class="active" aria-current="true" aria-label="Slide 3"></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Half and half carousel style ends -->

<!-- caption -->
<div id="recipe_caption" class="container-fluid text-center mt-4">
    <h1>Discover Recipes That Inspire Every Meal!</h1>
    <p class="lead">All the Flavors You Crave, All in One Place – Dive Into Our Delicious Collection of Recipes!</p>
    
</div>


<!-- Recipe Posts -->
<div class="container-fluid mt-3 mb-4">
    <div class="row">

        <!-- Recipe Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for recipe in recipe_list %}
                <div class="col-md-4">
                    <div class="card mb-4 recipe-entry">
                        <div class="card-body">
                            <div class="image-container mb-3">
                                {% if "placeholder" in recipe.featured_image.url %}
                                <img class="card-img-top" src="{% static 'images/default.jpg' %}"
                                    alt="placeholder image">
                                {% else %}
                                <img class="card-img-top" src=" {{ recipe.featured_image.url }}" alt="{{ recipe.recipe_title }}">
                                {% endif %}
                                
                            </div>
                            <a href="{% url 'recipe_detail' recipe.slug %}" class="recipe-link">
                                <h2 class="card-title">{{ recipe.recipe_title }}</h2>
                            </a>
                            <p class="introduction">{{ recipe.introduction }}
                                </p>

                            <hr>
                            <div class="image-flash d-flex justify-content-between align-items-center">
                                <p class="author mb-0">Recipe By: <strong>{{ recipe.author }}</strong></p>
                                <p class="card-text text-muted h6 mb-0">{{ recipe.get_diet_display}}
                                </p>
                            </div>
                            
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV</a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{% endblock %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'js/comments.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

recipe/templates/recipe/recipe_detail.html
{% extends 'base.html' %}
{% block title %}Recipe Detail{% endblock %}
{% block content %}

{% load static %}
{% load crispy_forms_tags %}

{% block link %}
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}


 <!-- Display messages -->
 {% if messages %}
 <div class="alert alert-info mt-3" role="alert">
     {% for message in messages %}
     <div>{{ message }}</div>
     {% endfor %}
    </div>
    {% endif %}
<!-- Masthead Section -->
<div class="masthead">
    <div class="container mt-3">
        <div class="row g-0 align-items-stretch">
            <div class="col-md-12 d-flex flex-column">
                <!-- Card Column: Text + Image Together -->
                <div class="card mb-4 mt-3 left top flex-fill glow-card">
                    <div class="row g-0">
                        <!-- Text Column -->
                        <div class="col-md-6 d-flex align-items-start justify-content-center">
                            <div class="card-body p-4" id="recipeCard">

                                <!-- Recipe title goes in these h1 tags -->
                                <h1 class="recipe-title">{{ recipe.recipe_title }}
                                    
                                </h1>
                                
                                <p><strong class="text-secondary">
                                        <a href="#reviews" class="text-decoration-none link-success"> <i
                                                class="bi bi-chat-fill"></i> {{ comment_count }}</a>
                                                <button  id="printButton" class="btn btn-primary btn-sm ms-3 bg-warning text-dark"><i class="bi bi-printer-fill"></i></button>
                                                
                                                <button type="button"  class="btn btn-primary ms-3 bg-warning text-dark"  data-bs-toggle="modal" data-bs-target="#reviewModal">Review</button>
                                                
                                    </strong></p>
                                <hr>
                                <!-- Introduction Section -->
                                <h5 class="card-title">Introduction</h5>
                                <p class="card-text">{{ recipe.introduction | safe }}</p>
                                <hr>
                                <!-- Ingredients Section -->
                                <h5 class="card-title">Ingredients</h5>
                                <p class="card-text">{{ recipe.ingredients | safe }}</p>
                                <hr>
                                <!-- Instructions Section -->
                                <h5 class="card-title">Instructions</h5>
                                <p class="card-text">{{ recipe.instructions | safe }}</p>
                            </div>
                        </div>
                        <!-- Image Column -->
                        <div class="col-md-6 masthead-image">
                            <img src="{{ recipe.featured_image.url }}" class="img-fluid"
                                alt="{{ recipe.recipe_title }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Displaying Comments -->
<div class="container mb-3">
    <div class="row g-0 align-items-stretch">
        <div class="col-md-12 d-flex flex-column">
            <div class="card mb-4 mt-3 left top flex-fill glow-card">
                <div class="row g-0">
                    <div class="col-md-12 d-flex align-items-start justify-content-center">
                        <div class="card-body p-4">
                            <h3 id="reviews">Reviews:</h3>
                            <hr>
                            {% for comment in comments %}
                            <div class="p-2 comments
          {% if not comment.approved and comment.author == user %}
          faded{% elif not comment.approved %} d-none{% endif %}">
                                <p class="font-weight-bold"><b>
                                        {{ comment.author }}</b> reviewed on
                                    <span class="font-weight-normal">
                                        <i> {{ comment.created_on }}</i>
                                    </span>
                                </p>
                                <div class="rating">
                                    {% for i in "12345" %}
                                    {% if i|add:"0" <= comment.rating %} <i class="bi bi-star-fill text-warning"></i>
                                        {% else %}
                                        <i class="bi bi-star"></i>
                                        {% endif %}
                                        {% endfor %}
                                        <div id="comment{{ comment.id }}">
                                            {{ comment.body | linebreaks }}
                                        </div>
                                        {% if not comment.approved and comment.author == user %}
                                        <p class="approval">
                                            Thanks for your review! It’s in the approval queue and will be live once it’s approved. Stay tuned!
                                        </p>
                                        {% endif %}
                                        {% if user.is_authenticated and comment.author == user %}
                                        <div class="row gap-3">
                                            <button class="btn btn-delete" comment_id="{{ comment.id }}">Delete</button>

                                            <button class="btn btn-edit"
                                            data-comment_id="{{ comment.id }}" data-bs-toggle="modal" data-bs-target="#reviewModal">Edit</button>
                                        </div>
                                        {% endif %}
                                    </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Review Modal -->

<div class="modal fade" id="reviewModal" tabindex="-1" aria-labelledby="reviewModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content card">
            <div class="modal-header">
                {% if user.is_authenticated %}
                <h3 class="modal-title" id="reviewModalLabel">Leave a Review</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                
                <form id="commentForm" method="post">
                    {% csrf_token %}
                    {{ comment_form.body|as_crispy_field }}
                    <p>Rating:</p>
                    <!-- Star rating inside the form -->
                    <div class="star-rating" id="starRating">
                        {% for i in "12345" %}
                            <i class="bi bi-star" data-value="{{ forloop.counter }}"></i>
                        {% endfor %}
                    </div>
                     <!-- Hidden rating input inside the form -->
    <input type="hidden" id="id_rating" name="rating" value="1">

                    <button id="submitButton" type="submit" class="btn btn-primary btn-signup">Submit</button>
                </form>
                {% else %}
                            <p class="text-center"><strong>Log in to leave a review</strong></h5>
                            {% endif %}
            </div>
        </div>
    </div>
</div>


<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content card">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete comment?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete your comment?
                This action cannot be undone.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
<script src="{% static 'js/comments.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}